# Generated by Django 2.2.3 on 2019-07-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRegistrado', models.DateField(auto_now=True)),
                ('cidade', models.CharField(max_length=200)),
            ],
        ),
    ]
